#!/bin/sh

hwclock -s

### network config
ifconfig lo 127.0.0.1
/sbin/net_set &
if [ ! -e /usr/sbin/inetd ]; then
	busybox --install
fi
/usr/sbin/inetd &

### hostname
/bin/hostname xprod

### start applications and services
/usr/bin/xupgrade
/usr/bin/xdrivers
/usr/bin/xprod
